vpc_cidr_block      = "10.0.0.0/16"
subnet_cidr_block   = "10.0.10.0/24"
avail_zone          = "us-east-1b"
env_prefix          = "dev"
my_ip               = "0.0.0.0/0"
instance_type       = "t2.micro"
public_key_location = "/home/khurd/.ssh/id_rsa.pub"
image_name          = "amzn2-ami-kernel-*-x86_64-gp2"
