vpc_cidr_block       = "10.0.0.0/16"
subnet_cidr_block    = "10.0.10.0/24"
avail_zone           = "us-east-1b"
env_prefix           = "dev"
my_ip                = "50.226.207.166/32"
instance_type        = "t2.micro"
public_key_location  = "/home/khurd/.ssh/id_rsa.pub"
private_key_location = "/home/khurd/.ssh/id_rsa"
